language: java

env:
  - secure: "VcFCgfU0RL8XIAurIktqdMwt7QkvEez/29VuPnoVEkjK5z2ckHUgFcORRWcZhJbXpQAFjPUQn04ZVRrcLJydhPpmHEX5DbJHU+cTtOesz9KtfPibBzVNfxpG8u00HI3QtpVI5B3uKXHNK87uqc7ZSucNIZVGpc2vWJojHDzxsr8="
  - secure: "IjHCo9VdTid/nvtzztcBSEpXvW4+oi9dXN6jOQ4VveljL/wWzKguI/DpsEteSDFxMkOb0MeaVfs/2ZfdIYBgDIXb2nTHWvd6nn5h20tuuQI+5wJC1XWomN4zNPp9bRLBs2zTLnYa9NgF/VdbUHZS3POxJqVeXVW9Kz4nhICKaV4="
  
after_success:
  - mvn clean test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
  
deploy:
  provider: releases
  api_key:
    secure: OIJ/1TSmr7eZ+6Nwpf3v1ly43rhQbpoEVITHvjs3H/RhcE7vfZEmJwmgGsx/QtSobrCQfU22VGIzppiV/s3TrtyEsfNlS9kroGizIHG5iv0Brb77/GiRoStudIMxtNsiRstivLxlePVOs2wRcXm2NvCqEkSLf11uhH5ciBfKsB0=
  file_glob: true
  file: target/*.jar
  
after_deploy:
    - openssl aes-256-cbc -K $encrypted_db61717a69e2_key -iv $encrypted_db61717a69e2_iv -in ossrh_keys.tar.gz.enc -out ossrh_keys.tar.gz -d
    - tar -zxvf ossrh_keys.tar.gz
    - gpg --import private.key && gpg --import public.key
    - echo "<settings><servers><server><id>ossrh</id><username>\${env.ossrh_username}</username><password>\${env.ossrh_password}</password></server></servers></settings>" > ~/settings.xml
    - mvn deploy -DskipTests=true -Dgpg.passphrase=$ossrh_password -s ~/settings.xml -PactivateDeploy