language: java

env:
  secure: "JOK91tQnG9qaFQtidimKZJR6GUtjZw09PQ5dMavk89as5A7M4f00xwVSBHNQMFgtLzuej4K/OXEbj6pwKpNaE9i04KrwShnaHNLS23ePI2yYTx9VwpEraGdkNO7fzZ8IC9cCg0j8iTVGU+qLSwZ5booLJxgGnJ8QirZ6rayY/4M="

after_success:
  - mvn clean test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OIJ/1TSmr7eZ+6Nwpf3v1ly43rhQbpoEVITHvjs3H/RhcE7vfZEmJwmgGsx/QtSobrCQfU22VGIzppiV/s3TrtyEsfNlS9kroGizIHG5iv0Brb77/GiRoStudIMxtNsiRstivLxlePVOs2wRcXm2NvCqEkSLf11uhH5ciBfKsB0=
  file_glob: true
  file: target/*.jar
  on:
    tags: true
    all_branches: true

after_deploy:
    - openssl aes-256-cbc -K $encrypted_db61717a69e2_key -iv $encrypted_db61717a69e2_iv -in ossrh_keys.tar.gz.enc -out ossrh_keys.tar.gz -d
    - tar -zxvf ossrh_keys.tar.gz
    - gpg --import private.key && gpg --import public.key
    - echo "<settings><servers><server><id>ossrh</id><username>\${env.ossrh_username}</username><password>\${env.ossrh_password}</password></server><server><id>gpg.passphrase</id><passphrase>\${env.gpg_password}</passphrase></server></servers></settings>" > ~/settings.xml
    - mvn deploy -DskipTests=true -s ~/settings.xml -PactivateDeploy
